# Setup
title:               Somehow I Manage
tagline:             'The story of my PhD'
description:         'This is my personal blog'
url:                 
baseurl:             ''
paginate:            1
permalink:           pretty

# About/contact
author:
  name:              Zhulien Zhelezchev
  url:              
  email:             

# Gems
plugins:
  - jekyll-paginate
  
# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
